//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by pikabelajar.rc
//
#define IDD_PIKABELAJAR_DIALOG          102
#define IDR_MAINFRAME                   128
#define IDR_PNG_INBACK                  129
#define IDR_PNG_OUTBACK                 130
#define IDD_PIKABELAJARIN_DIALOG        131
#define IDR_PNG_CLOSE_DLG               132
#define IDR_PNG_LEFT                    139
#define IDR_PNG_RIGHT                   140
#define IDR_PNG_SET1                    141
#define IDR_PNG_AA                      145
#define IDR_PNG_BB                      146
#define IDR_PNG_CC                      147
#define IDR_PNG_DD                      148
#define IDR_PNG_TANYA                   150
#define IDR_PNG_ZOOM                    151
#define IDD_DIALOG_PREVIEW              152
#define IDR_PNG_SERVERMANAGER           153
#define IDR_PNG_CLIENT                  154
#define IDR_PNG_HARGA                   155
#define IDR_PNG_MANAGERWARNET           156
#define IDR_PNG_ATURPC                  157
#define IDR_WAVE_SALAH                  160
#define IDR_WAVE_BENAR                  161
#define IDR_PNG_BTNCLOSE                166
#define IDR_GIF1                        171
#define IDR_GIF3                        173
#define IDR_GIF4                        174
#define IDR_GIF5                        175
#define IDR_GIF6                        176
#define IDR_GIF7                        177
#define IDR_GIF8                        178
#define IDR_GIF9                        179
#define IDR_GIF10                       180
#define IDR_GIF11                       181
#define IDR_GIF2                        182
#define IDD_DIALOG_HINTVIEW             185
#define IDB_SPLASH                      186
#define IDC_CURSORZOOM                  189
#define IDD_DIALOG_NOTICE               190
#define IDR_PNG_NOTICEA                 192
#define IDR_PNG_NOTICEB                 193
#define IDR_PNG_NOTICEC                 194
#define IDR_PNG_NOTICED                 195
#define IDD_DIALOG_BTN                  196
#define IDB_BITMAP1                     197
#define IDB_BITMAP_TRANSCLOSE           199
#define IDR_PNG_RESULT                  200
#define IDD_DIALOG_RESULT               201
#define IDR_PNG_ULANG                   203
#define IDR_PNG_LANJUK                  204
#define IDR_PNG_YM1                     205
#define IDR_PNG_YM2                     206
#define IDR_PNG_FACEBOOK                207
#define IDR_PNG_YOUTUBE                 208
#define IDD_DIALOG_PLAY                 209
#define IDB_VOL_FILL                    211
#define IDB_VOL_KNOB                    212
#define IDR_PNG_PLAYMUSIC               215
#define IDD_DIALOG_PLAYLAYER            216
#define IDR_PNG_SKINLAYER               217
#define IDR_PNG_SKININ                  218
#define IDR_PNG_MUSIC_LEFT              219
#define IDR_PNG_MUSIC_RIGHT             220
#define IDR_PNG_PLAYMUSIC_STOP          221
#define IDR_PNG_SUARAPLUS               222
#define IDR_PNG_SUARAMIN                223
#define IDR_PNG_ADDFOLDER               224
#define IDR_PNG_PLAY                    225
#define IDR_PNG_MAN                     228
#define IDR_PNG_WOMAN                   229
#define IDR_WAVE_BENAR_ADI              230
#define IDR_WAVE_SALAH_ADI              231
#define IDR_WAVE_BENAR_DESITA           232
#define IDR_WAVE_SALAH_DESITA           233
#define IDR_WAVE_BENAR_PUTRI            234
#define IDR_WAVE_SALAH_PUTRI            235
#define IDR_WAVE_DATANG_ADI             236
#define IDR_WAVE_DATANG_DESITA          237
#define IDR_WAVE_DATANG_PUTRI           238
#define IDR_WAVE_JUMPA_ADI              239
#define IDR_WAVE_JUMPA_DESITA           240
#define IDR_WAVE_JUMPA_PUTRI            241
#define IDC_BUTTON_CLOSE                1000
#define IDC_STATIC_BANNER               1001
#define IDC_BUTTON_LEFT                 1001
#define IDC_STATIC_DISPICTURE           1002
#define IDC_BUTTON_RIGHT                1002
#define IDC_STATIC_TANYA                1003
#define IDC_BUTTON_SETTING1             1003
#define IDC_STATIC_JAWAB1               1004
#define IDC_BUTTON_SETTING2             1004
#define IDC_STATIC_JAWAB2               1005
#define IDC_BUTTON_SETTING3             1005
#define IDC_STATIC_JAWAB3               1006
#define IDC_BUTTON_SETTING4             1006
#define IDC_STATIC_JAWAB4               1007
#define IDC_BUTTON_SETTING5             1007
#define IDC_BUTTON_JAWAB1               1008
#define IDC_BUTTON_MUSIC                1008
#define IDC_BUTTON_JAWAB2               1009
#define IDC_STATIC_PREVIEW              1009
#define IDC_BUTTON_SUARALAKI            1009
#define IDC_BUTTON_JAWAB3               1010
#define IDC_BUTTON_SUARAPUTRI           1010
#define IDC_BUTTON_JAWAB4               1011
#define IDC_STATIC_SPLASH               1012
#define IDC_IMAGE                       1012
#define IDC_BUTTON_TANYA                1013
#define IDC_STATIC_MESSAGE              1013
#define IDC_BUTTON_ZOOM                 1014
#define IDC_STATIC_MESSAGE2             1014
#define IDC_STATIC_HINTIMAGE            1015
#define IDC_STATIC_MESSAGE3             1015
#define IDC_BUTTON_ULANG                1016
#define IDC_BUTTON_LANGJUT              1017
#define IDC_BUTTON_YM1                  1017
#define IDC_BUTTON_YM2                  1018
#define IDC_BUTTON_YOUTUBE              1019
#define IDC_BUTTON_FACEBOOK             1020
#define IDC_SLIDER1                     1021
#define IDC_VOLUME                      1022
#define IDC_BUTTON_PHILIHFOLDER         1023
#define IDC_STATIC_TIME                 1024
#define IDC_BUTTON_PLAY                 1025
#define IDC_BUTTON_PLAYLEFT             1026
#define IDC_BUTTON_PLAYNEXT             1027
#define IDC_BUTTON_PLAYSTOP             1028
#define IDC_BUTTON_SUARAPLUS            1029
#define IDC_BUTTON_SUARAMIN             1030
#define IDC_STATIC_SEARCH               1031

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        242
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1030
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
